version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: clubs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clubs_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clubs-network

volumes:
  postgres_data:

networks:
  clubs-network:
    driver: bridge
