import { SidebarItem, App, RecentFile, Project, Tutorial, CommunityPost, Member, User, Sponsor, Payment, Permission, Role } from "./types"

// Sample data for apps
export const apps: App[] = [
    {
        name: "PixelMaster",
        icon: "ImageIcon",
        description: "Advanced image editing and composition",
        category: "Creative",
        recent: true,
        new: false,
        progress: 100,
    },
    {
        name: "VectorPro",
        icon: "Brush",
        description: "Professional vector graphics creation",
        category: "Creative",
        recent: true,
        new: false,
        progress: 100,
    },
    {
        name: "VideoStudio",
        icon: "Video",
        description: "Cinematic video editing and production",
        category: "Video",
        recent: true,
        new: false,
        progress: 100,
    },
    {
        name: "MotionFX",
        icon: "Sparkles",
        description: "Stunning visual effects and animations",
        category: "Video",
        recent: false,
        new: false,
        progress: 100,
    },
    {
        name: "PageCraft",
        icon: "Layers",
        description: "Professional page design and layout",
        category: "Creative",
        recent: false,
        new: false,
        progress: 100,
    },
    {
        name: "UXFlow",
        icon: "LayoutGrid",
        description: "Intuitive user experience design",
        category: "Design",
        recent: false,
        new: true,
        progress: 85,
    },
    {
        name: "PhotoLab",
        icon: "Camera",
        description: "Advanced photo editing and organization",
        category: "Photography",
        recent: false,
        new: false,
        progress: 100,
    },
    {
        name: "DocMaster",
        icon: "FileText",
        description: "Document editing and management",
        category: "Document",
        recent: false,
        new: false,
        progress: 100,
    },
    {
        name: "WebCanvas",
        icon: "Code",
        description: "Web design and development",
        category: "Web",
        recent: false,
        new: true,
        progress: 70,
    },
    {
        name: "3DStudio",
        icon: "CuboidIcon",
        description: "3D modeling and rendering",
        category: "3D",
        recent: false,
        new: true,
        progress: 60,
    },
    {
        name: "FontForge",
        icon: "Type",
        description: "Typography and font creation",
        category: "Typography",
        recent: false,
        new: false,
        progress: 100,
    },
    {
        name: "ColorPalette",
        icon: "Palette",
        description: "Color scheme creation and management",
        category: "Design",
        recent: false,
        new: false,
        progress: 100,
    },
]

// Sample data for recent files
export const recentFiles: RecentFile[] = [
    {
        name: "Brand Redesign.pxm",
        app: "PixelMaster",
        modified: "2 hours ago",
        icon: "ImageIcon",
        shared: true,
        size: "24.5 MB",
        collaborators: 3,
    },
    {
        name: "Company Logo.vec",
        app: "VectorPro",
        modified: "Yesterday",
        icon: "Brush",
        shared: true,
        size: "8.2 MB",
        collaborators: 2,
    },
    {
        name: "Product Launch Video.vid",
        app: "VideoStudio",
        modified: "3 days ago",
        icon: "Video",
        shared: false,
        size: "1.2 GB",
        collaborators: 0,
    },
    {
        name: "UI Animation.mfx",
        app: "MotionFX",
        modified: "Last week",
        icon: "Sparkles",
        shared: true,
        size: "345 MB",
        collaborators: 4,
    },
    {
        name: "Magazine Layout.pgc",
        app: "PageCraft",
        modified: "2 weeks ago",
        icon: "Layers",
        shared: false,
        size: "42.8 MB",
        collaborators: 0,
    },
    {
        name: "Mobile App Design.uxf",
        app: "UXFlow",
        modified: "3 weeks ago",
        icon: "LayoutGrid",
        shared: true,
        size: "18.3 MB",
        collaborators: 5,
    },
    {
        name: "Product Photography.phl",
        app: "PhotoLab",
        modified: "Last month",
        icon: "Camera",
        shared: false,
        size: "156 MB",
        collaborators: 0,
    },
]

// Sample data for projects
export const projects: Project[] = [
    {
        name: "Website Redesign",
        description: "Complete overhaul of company website",
        progress: 75,
        dueDate: "June 15, 2025",
        members: 4,
        files: 23,
    },
    {
        name: "Mobile App Launch",
        description: "Design and assets for new mobile application",
        progress: 60,
        dueDate: "July 30, 2025",
        members: 6,
        files: 42,
    },
    {
        name: "Brand Identity",
        description: "New brand guidelines and assets",
        progress: 90,
        dueDate: "May 25, 2025",
        members: 3,
        files: 18,
    },
    {
        name: "Marketing Campaign",
        description: "Summer promotion materials",
        progress: 40,
        dueDate: "August 10, 2025",
        members: 5,
        files: 31,
    },
]

// Sample data for tutorials
export const tutorials: Tutorial[] = [
    {
        title: "Mastering Digital Illustration",
        description: "Learn advanced techniques for creating stunning digital art",
        duration: "1h 45m",
        level: "Advanced",
        instructor: "Sarah Chen",
        category: "Illustration",
        views: "24K",
    },
    {
        title: "UI/UX Design Fundamentals",
        description: "Essential principles for creating intuitive user interfaces",
        duration: "2h 20m",
        level: "Intermediate",
        instructor: "Michael Rodriguez",
        category: "Design",
        views: "56K",
    },
    {
        title: "Video Editing Masterclass",
        description: "Professional techniques for cinematic video editing",
        duration: "3h 10m",
        level: "Advanced",
        instructor: "James Wilson",
        category: "Video",
        views: "32K",
    },
    {
        title: "Typography Essentials",
        description: "Create beautiful and effective typography for any project",
        duration: "1h 30m",
        level: "Beginner",
        instructor: "Emma Thompson",
        category: "Typography",
        views: "18K",
    },
    {
        title: "Color Theory for Designers",
        description: "Understanding color relationships and psychology",
        duration: "2h 05m",
        level: "Intermediate",
        instructor: "David Kim",
        category: "Design",
        views: "41K",
    },
]

// Sample data for community posts
export const communityPosts: CommunityPost[] = [
    {
        title: "Minimalist Logo Design",
        author: "Alex Morgan",
        likes: 342,
        comments: 28,
        image: "/placeholder.svg?height=300&width=400",
        time: "2 days ago",
    },
    {
        title: "3D Character Concept",
        author: "Priya Sharma",
        likes: 518,
        comments: 47,
        image: "/placeholder.svg?height=300&width=400",
        time: "1 week ago",
    },
    {
        title: "UI Dashboard Redesign",
        author: "Thomas Wright",
        likes: 276,
        comments: 32,
        image: "/placeholder.svg?height=300&width=400",
        time: "3 days ago",
    },
    {
        title: "Product Photography Setup",
        author: "Olivia Chen",
        likes: 189,
        comments: 15,
        image: "/placeholder.svg?height=300&width=400",
        time: "5 days ago",
    },
]

// Sample data for sidebar navigation
export const sidebarItems: SidebarItem[] = [
    {
        title: "Home",
        icon: "Home",
        isActive: true,
    },
    {
        title: "Members",
        icon: "Users",
        badge: "8",
    },
    {
        title: "Users",
        icon: "UserPlus",
        badge: "5",
    },
    {
        title: "Sponsors",
        icon: "Building",
        badge: "4",
    },
    {
        title: "Payments",
        icon: "DollarSign",
        badge: "6",
    },
    {
        title: "Roles",
        icon: "ShieldCheck",
        badge: "3",
    },
    {
        title: "Permissions",
        icon: "Settings",
        badge: "16",
    },
]

// Sample data for members
export const members: Member[] = [
    {
        id: "1",
        name: "Sarah Chen",
        email: "sarah.chen@designali.com",
        role: "Senior UI/UX Designer",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "March 2023",
        lastActive: "2 hours ago",
        projects: 8,
        skills: ["Figma", "Sketch", "Adobe XD", "Prototyping", "User Research"],
        department: "Design",
        phone: "+1 (555) 123-4567",
        location: "San Francisco, CA",
    },
    {
        id: "2",
        name: "Michael Rodriguez",
        email: "michael.rodriguez@designali.com",
        role: "Creative Director",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "January 2022",
        lastActive: "1 day ago",
        projects: 12,
        skills: ["Creative Direction", "Brand Strategy", "Team Leadership", "Adobe Creative Suite"],
        department: "Creative",
        phone: "+1 (555) 234-5678",
        location: "New York, NY",
    },
    {
        id: "3",
        name: "Emma Thompson",
        email: "emma.thompson@designali.com",
        role: "Graphic Designer",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "June 2023",
        lastActive: "30 minutes ago",
        projects: 5,
        skills: ["Illustrator", "Photoshop", "InDesign", "Typography", "Print Design"],
        department: "Design",
        phone: "+1 (555) 345-6789",
        location: "Los Angeles, CA",
    },
    {
        id: "4",
        name: "David Kim",
        email: "david.kim@designali.com",
        role: "Motion Graphics Artist",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "September 2023",
        lastActive: "3 hours ago",
        projects: 6,
        skills: ["After Effects", "Cinema 4D", "Motion Design", "3D Animation"],
        department: "Motion",
        phone: "+1 (555) 456-7890",
        location: "Austin, TX",
    },
    {
        id: "5",
        name: "Priya Sharma",
        email: "priya.sharma@designali.com",
        role: "Product Designer",
        status: "pending",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "December 2024",
        lastActive: "1 week ago",
        projects: 2,
        skills: ["Product Design", "User Experience", "Prototyping", "Design Systems"],
        department: "Product",
        phone: "+1 (555) 567-8901",
        location: "Seattle, WA",
    },
    {
        id: "6",
        name: "Alex Morgan",
        email: "alex.morgan@designali.com",
        role: "Frontend Developer",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "April 2023",
        lastActive: "5 minutes ago",
        projects: 10,
        skills: ["React", "TypeScript", "CSS", "JavaScript", "UI Development"],
        department: "Engineering",
        phone: "+1 (555) 678-9012",
        location: "Boston, MA",
    },
    {
        id: "7",
        name: "Olivia Chen",
        email: "olivia.chen@designali.com",
        role: "Marketing Designer",
        status: "inactive",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "February 2023",
        lastActive: "2 weeks ago",
        projects: 4,
        skills: ["Marketing Design", "Social Media", "Branding", "Adobe Creative Suite"],
        department: "Marketing",
        phone: "+1 (555) 789-0123",
        location: "Chicago, IL",
    },
    {
        id: "8",
        name: "Thomas Wright",
        email: "thomas.wright@designali.com",
        role: "3D Artist",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "July 2023",
        lastActive: "1 hour ago",
        projects: 7,
        skills: ["Blender", "Maya", "3D Modeling", "Texturing", "Rendering"],
        department: "3D",
        phone: "+1 (555) 890-1234",
        location: "Portland, OR",
    },
]

// Sample data for users
export const users: User[] = [
    {
        id: "1",
        username: "admin",
        email: "admin@designali.com",
        fullName: "Administrator",
        role: "admin",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "January 2022",
        lastLogin: "2 hours ago",
        permissions: ["all"],
        department: "IT",
        phone: "+1 (555) 000-0001",
        location: "San Francisco, CA",
    },
    {
        id: "2",
        username: "manager1",
        email: "manager@designali.com",
        fullName: "John Manager",
        role: "manager",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "March 2023",
        lastLogin: "1 day ago",
        permissions: ["read", "write", "delete"],
        department: "Management",
        phone: "+1 (555) 000-0002",
        location: "New York, NY",
    },
    {
        id: "3",
        username: "user1",
        email: "user@designali.com",
        fullName: "Alice User",
        role: "user",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "June 2023",
        lastLogin: "30 minutes ago",
        permissions: ["read", "write"],
        department: "Design",
        phone: "+1 (555) 000-0003",
        location: "Los Angeles, CA",
    },
    {
        id: "4",
        username: "guest1",
        email: "guest@designali.com",
        fullName: "Bob Guest",
        role: "guest",
        status: "active",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "September 2023",
        lastLogin: "1 week ago",
        permissions: ["read"],
        department: "Marketing",
        phone: "+1 (555) 000-0004",
        location: "Chicago, IL",
    },
    {
        id: "5",
        username: "suspended1",
        email: "suspended@designali.com",
        fullName: "Charlie Suspended",
        role: "user",
        status: "suspended",
        avatar: "/placeholder.svg?height=40&width=40",
        joinDate: "April 2023",
        lastLogin: "2 weeks ago",
        permissions: ["read"],
        department: "Engineering",
        phone: "+1 (555) 000-0005",
        location: "Boston, MA",
    },
]

// Sample data for sponsors
export const sponsors: Sponsor[] = [
    {
        id: "1",
        name: "TechCorp",
        company: "TechCorp Industries",
        email: "sponsor@techcorp.com",
        phone: "+1 (555) 100-0001",
        website: "https://techcorp.com",
        logo: "/placeholder.svg?height=40&width=40",
        status: "active",
        sponsorshipLevel: "platinum",
        startDate: "2024-01-01",
        endDate: "2024-12-31",
        amount: 50000,
        currency: "USD",
        description: "Platinum sponsorship for annual events",
        contactPerson: "Sarah Johnson",
        notes: "Very reliable sponsor, always pays on time",
    },
    {
        id: "2",
        name: "DesignHub",
        company: "DesignHub Creative",
        email: "partnership@designhub.com",
        phone: "+1 (555) 100-0002",
        website: "https://designhub.com",
        logo: "/placeholder.svg?height=40&width=40",
        status: "active",
        sponsorshipLevel: "gold",
        startDate: "2024-03-01",
        endDate: "2024-08-31",
        amount: 25000,
        currency: "USD",
        description: "Gold sponsorship for design workshops",
        contactPerson: "Mike Chen",
        notes: "Interested in expanding partnership",
    },
    {
        id: "3",
        name: "InnovateLab",
        company: "InnovateLab Solutions",
        email: "contact@innovatelab.com",
        phone: "+1 (555) 100-0003",
        website: "https://innovatelab.com",
        logo: "/placeholder.svg?height=40&width=40",
        status: "pending",
        sponsorshipLevel: "silver",
        startDate: "2024-06-01",
        endDate: "2024-11-30",
        amount: 15000,
        currency: "USD",
        description: "Silver sponsorship for innovation events",
        contactPerson: "Lisa Wang",
        notes: "New sponsor, needs follow-up",
    },
    {
        id: "4",
        name: "CreativeFlow",
        company: "CreativeFlow Agency",
        email: "hello@creativeflow.com",
        phone: "+1 (555) 100-0004",
        website: "https://creativeflow.com",
        logo: "/placeholder.svg?height=40&width=40",
        status: "inactive",
        sponsorshipLevel: "bronze",
        startDate: "2023-09-01",
        endDate: "2024-02-29",
        amount: 5000,
        currency: "USD",
        description: "Bronze sponsorship for creative events",
        contactPerson: "David Kim",
        notes: "Contract expired, considering renewal",
    },
]

// Sample data for payments
export const payments: Payment[] = [
    {
        id: "1",
        memberId: "1",
        memberName: "Sarah Chen",
        amount: 150,
        currency: "USD",
        status: "completed",
        paymentMethod: "credit_card",
        transactionId: "TXN-001-2024",
        date: "2024-01-15",
        dueDate: "2024-01-15",
        description: "Annual membership fee",
        category: "membership",
        receiptUrl: "/receipts/txn-001.pdf",
        notes: "Paid on time",
    },
    {
        id: "2",
        memberId: "2",
        memberName: "Michael Rodriguez",
        amount: 75,
        currency: "USD",
        status: "pending",
        paymentMethod: "bank_transfer",
        transactionId: "TXN-002-2024",
        date: "2024-01-20",
        dueDate: "2024-01-25",
        description: "Workshop registration fee",
        category: "event",
        notes: "Awaiting bank confirmation",
    },
    {
        id: "3",
        memberId: "3",
        memberName: "Emma Thompson",
        amount: 200,
        currency: "USD",
        status: "completed",
        paymentMethod: "paypal",
        transactionId: "TXN-003-2024",
        date: "2024-01-18",
        dueDate: "2024-01-18",
        description: "Premium membership upgrade",
        category: "membership",
        receiptUrl: "/receipts/txn-003.pdf",
        notes: "Upgraded from basic to premium",
    },
    {
        id: "4",
        memberId: "4",
        memberName: "David Kim",
        amount: 50,
        currency: "USD",
        status: "failed",
        paymentMethod: "credit_card",
        transactionId: "TXN-004-2024",
        date: "2024-01-22",
        dueDate: "2024-01-22",
        description: "Event ticket",
        category: "event",
        notes: "Card declined, needs follow-up",
    },
    {
        id: "5",
        memberId: "5",
        memberName: "Priya Sharma",
        amount: 100,
        currency: "USD",
        status: "refunded",
        paymentMethod: "credit_card",
        transactionId: "TXN-005-2024",
        date: "2024-01-10",
        dueDate: "2024-01-10",
        description: "Workshop fee",
        category: "event",
        receiptUrl: "/receipts/txn-005.pdf",
        notes: "Refunded due to cancellation",
    },
    {
        id: "6",
        memberId: "6",
        memberName: "Alex Morgan",
        amount: 300,
        currency: "USD",
        status: "completed",
        paymentMethod: "cash",
        transactionId: "TXN-006-2024",
        date: "2024-01-25",
        dueDate: "2024-01-25",
        description: "Annual membership + events package",
        category: "membership",
        receiptUrl: "/receipts/txn-006.pdf",
        notes: "Paid in cash at office",
    },
]

// Sample data for permissions
export const permissions: Permission[] = [
    {
        id: "1",
        name: "users.read",
        description: "Leer información de usuarios"
    },
    {
        id: "2",
        name: "users.create",
        description: "Crear nuevos usuarios"
    },
    {
        id: "3",
        name: "users.update",
        description: "Actualizar información de usuarios"
    },
    {
        id: "4",
        name: "users.delete",
        description: "Eliminar usuarios"
    },
    {
        id: "5",
        name: "members.read",
        description: "Leer información de miembros"
    },
    {
        id: "6",
        name: "members.create",
        description: "Crear nuevos miembros"
    },
    {
        id: "7",
        name: "members.update",
        description: "Actualizar información de miembros"
    },
    {
        id: "8",
        name: "members.delete",
        description: "Eliminar miembros"
    },
    {
        id: "9",
        name: "roles.read",
        description: "Leer información de roles"
    },
    {
        id: "10",
        name: "roles.create",
        description: "Crear nuevos roles"
    },
    {
        id: "11",
        name: "roles.update",
        description: "Actualizar información de roles"
    },
    {
        id: "12",
        name: "roles.delete",
        description: "Eliminar roles"
    },
    {
        id: "13",
        name: "permissions.read",
        description: "Leer información de permisos"
    },
    {
        id: "14",
        name: "permissions.create",
        description: "Crear nuevos permisos"
    },
    {
        id: "15",
        name: "permissions.update",
        description: "Actualizar información de permisos"
    },
    {
        id: "16",
        name: "permissions.delete",
        description: "Eliminar permisos"
    }
]

// Sample data for roles
export const roles: Role[] = [
    {
        id: "1",
        name: "ADMIN",
        clubId: "club-1",
        permissions: [
            { id: "1", name: "users.read", description: "Leer información de usuarios" },
            { id: "2", name: "users.create", description: "Crear nuevos usuarios" },
            { id: "3", name: "users.update", description: "Actualizar información de usuarios" },
            { id: "4", name: "users.delete", description: "Eliminar usuarios" },
            { id: "5", name: "members.read", description: "Leer información de miembros" },
            { id: "6", name: "members.create", description: "Crear nuevos miembros" },
            { id: "7", name: "members.update", description: "Actualizar información de miembros" },
            { id: "8", name: "members.delete", description: "Eliminar miembros" },
            { id: "9", name: "roles.read", description: "Leer información de roles" },
            { id: "10", name: "roles.create", description: "Crear nuevos roles" },
            { id: "11", name: "roles.update", description: "Actualizar información de roles" },
            { id: "12", name: "roles.delete", description: "Eliminar roles" },
            { id: "13", name: "permissions.read", description: "Leer información de permisos" },
            { id: "14", name: "permissions.create", description: "Crear nuevos permisos" },
            { id: "15", name: "permissions.update", description: "Actualizar información de permisos" },
            { id: "16", name: "permissions.delete", description: "Eliminar permisos" }
        ]
    },
    {
        id: "2",
        name: "MANAGER",
        clubId: "club-1",
        permissions: [
            { id: "1", name: "users.read", description: "Leer información de usuarios" },
            { id: "2", name: "users.create", description: "Crear nuevos usuarios" },
            { id: "3", name: "users.update", description: "Actualizar información de usuarios" },
            { id: "5", name: "members.read", description: "Leer información de miembros" },
            { id: "6", name: "members.create", description: "Crear nuevos miembros" },
            { id: "7", name: "members.update", description: "Actualizar información de miembros" },
            { id: "9", name: "roles.read", description: "Leer información de roles" },
            { id: "13", name: "permissions.read", description: "Leer información de permisos" }
        ]
    },
    {
        id: "3",
        name: "MEMBER",
        clubId: "club-1",
        permissions: [
            { id: "1", name: "users.read", description: "Leer información de usuarios" },
            { id: "5", name: "members.read", description: "Leer información de miembros" }
        ]
    }
] 